[package]
name = "auth_xmppmessage"
version = "0.1.0"
authors = ["Yves Fischer <yvesf+git@xapek.org>"]
build = "build.rs"

[dependencies]
conduit = "0.7.4"
civet = "0.8.3"
time = "0.1.35"
base64 = "0.2.1"
rust-crypto = "0.2.36"
rand = "0.3"
getopts = "0.2"

[build-dependencies]
gcc = "0.3.35"